# Generated by Django 3.0.7 on 2022-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_answer_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
